// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: map_str_int.proto
// Protobuf Java Version: 4.29.3

package com.johnsnowlabs.proto;

public interface MapStrIntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.johnsnowlabs.proto.MapStrInt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, int32&gt; data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, int32&gt; data = 1;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getData();
  /**
   * <code>map&lt;string, int32&gt; data = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getDataMap();
  /**
   * <code>map&lt;string, int32&gt; data = 1;</code>
   */
  int getDataOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; data = 1;</code>
   */
  int getDataOrThrow(
      java.lang.String key);
}
