// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: map_str_int.proto
// Protobuf Java Version: 4.29.3

package com.johnsnowlabs.proto;

public final class MapStrIntProto {
  private MapStrIntProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MapStrIntProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_johnsnowlabs_proto_MapStrInt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_johnsnowlabs_proto_MapStrInt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_johnsnowlabs_proto_MapStrInt_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_johnsnowlabs_proto_MapStrInt_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021map_str_int.proto\022\026com.johnsnowlabs.pr" +
      "oto\"s\n\tMapStrInt\0229\n\004data\030\001 \003(\0132+.com.joh" +
      "nsnowlabs.proto.MapStrInt.DataEntry\032+\n\tD" +
      "ataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001" +
      "B*\n\026com.johnsnowlabs.protoB\016MapStrIntPro" +
      "toP\001b\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_johnsnowlabs_proto_MapStrInt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_johnsnowlabs_proto_MapStrInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_johnsnowlabs_proto_MapStrInt_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_johnsnowlabs_proto_MapStrInt_DataEntry_descriptor =
      internal_static_com_johnsnowlabs_proto_MapStrInt_descriptor.getNestedTypes().get(0);
    internal_static_com_johnsnowlabs_proto_MapStrInt_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_johnsnowlabs_proto_MapStrInt_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
